In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
df=pd.read_csv("wine_data.csv", header=None,usecols=[0,1,2])
df.columns=['Class label','Alcohol','Malic Acid']
df.sample(5)

     Class label  Alcohol  Malic Acid
8              1    14.83        1.64
5              1    14.20        1.76
39             1    14.22        3.99
47             1    13.90        1.68
118            2    12.77        3.43

# Train-Test-Split

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop('Class label',axis=1),
                                               df['Class label'],
                                               test_size=0.3,
                                               random_state=0)
X_train.shape , X_test.shape

((124, 2), (54, 2))

# Normalization

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

# converting to DataSet

In [20]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns)

In [24]:
np.round(X_train.describe(),1)

       Alcohol  Malic Acid
count    124.0       124.0
mean      13.0         2.4
std        0.8         1.1
min       11.0         0.9
25%       12.4         1.6
50%       13.0         1.9
75%       13.6         3.2
max       14.8         5.6

In [23]:
np.round(X_train_scaled.describe(),1)

       Alcohol  Malic Acid
count    124.0       124.0
mean       0.5         0.3
std        0.2         0.2
min        0.0         0.0
25%        0.4         0.2
50%        0.5         0.2
75%        0.7         0.5
max        1.0         1.0