In [1]:
import numpy as np 
import pandas as pd
import matplotlib as plt

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [6]:
df=pd.read_csv('titanic_toy.csv')

In [8]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [10]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [11]:
# using pandas

In [17]:
df['Age_99']=df['Age'].fillna(99)
df['Age_minus1']=df['Age'].fillna(-1)
df['Fare_999']=df['Fare'].fillna(999)
df.sample(15)

      Age     Fare  Family  Survived  Age_99  Age_minus1  Fare_999
119   2.0  31.2750       6         0     2.0         2.0   31.2750
300   NaN   7.7500       0         1    99.0        -1.0    7.7500
731  11.0  18.7875       0         0    11.0        11.0   18.7875
281  28.0      NaN       0         0    28.0        28.0  999.0000
529  23.0  11.5000       3         0    23.0        23.0   11.5000
365  30.0   7.2500       0         0    30.0        30.0    7.2500
717  27.0  10.5000       0         1    27.0        27.0   10.5000
424  18.0  20.2125       2         0    18.0        18.0   20.2125
272  41.0  19.5000       1         1    41.0        41.0   19.5000
411   NaN   6.8583       0         0    99.0        -1.0    6.8583
860  41.0      NaN       2         0    41.0        41.0  999.0000
618   4.0  39.0000       3         1     4.0         4.0   39.0000
663  36.0   7.4958       0         0    36.0        36.0    7.4958
699  42.0   7.6500       0         0    42.0        42.0    7.6500
167  45.0  27.9000       5         0    45.0        45.0   27.9000

In [26]:
# using scikit learn:
df2=pd.read_csv('titanic_toy.csv')

In [28]:
X_train,X_test,y_train,y_test=train_test_split(df2.drop(['Survived'],axis=1),
                                               df2['Survived'],
                                               test_size=.3,
                                               random_state=42)
X_train.shape, X_test.shape, y_train.shape,y_test.shape

((623, 3), (268, 3), (623,), (268,))

In [33]:
imputer1=SimpleImputer(strategy='constant',fill_value=99)
imputer2=SimpleImputer(strategy='constant',fill_value=999)

In [40]:
trf=ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare'])],
    remainder='passthrough')

In [41]:
X_train_transformed=trf.fit_transform(X_train)
X_test_transformed=trf.transform(X_test)

In [42]:
X_train_tr

      Age      Fare  Family
445   4.0   81.8583       2
650   NaN    7.8958       0
172   1.0   11.1333       2
450  36.0   27.7500       3
314  43.0   26.2500       2
..    ...       ...     ...
106  21.0    7.6500       0
270   NaN   31.0000       0
860  41.0       NaN       2
435  14.0  120.0000       3
102  21.0   77.2875       1

[623 rows x 3 columns]