In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
df=pd.read_csv('titanic_toy.csv')

In [28]:
df.head(5)
df.sample(10)

       Age      Fare  Family  Survived
713  29.00    9.4833       0         0
755   0.67   14.5000       2         1
839    NaN   29.7000       0         1
408  21.00    7.7750       0         0
347    NaN   16.1000       1         1
498  25.00  151.5500       3         0
873  47.00    9.0000       0         0
164   1.00   39.6875       5         0
397  46.00   26.0000       0         0
636  32.00    7.9250       0         0

In [29]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [31]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [32]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)
X_train.shape, y_train.shape

((712, 3), (712,))

In [33]:
mean_age=df['Age'].mean()
median_age=df['Age'].median()
mean_fare=df['Fare'].mean()
median_fare=df['Fare'].median()

In [38]:
df['Age_mean']=df['Age'].fillna(mean_age)
df['Age_median']=df['Age'].fillna(median_age)
df['Fare_mean']=df['Fare'].fillna(mean_fare)
df['Fare_median']=df['Fare'].fillna(median_fare)

In [39]:
df.sample(15)

,Age,Fare,Family,Survived,Age_mean,Age_median,Fare_mean,Fare_median
104,37.00,7.9250,2,0,37.000000,37.00,7.925000,7.9250
748,19.00,53.1000,1,0,19.000000,19.00,53.100000,53.1000
608,22.00,41.5792,3,1,22.000000,22.00,41.579200,41.5792
436,21.00,34.3750,4,0,21.000000,21.00,34.375000,34.3750
456,65.00,26.5500,0,0,65.000000,65.00,26.550000,26.5500
178,30.00,13.0000,0,0,30.000000,30.00,13.000000,13.0000
413,NaN,0.0000,0,0,29.699118,28.00,0.000000,0.0000
789,46.00,79.2000,0,0,46.000000,46.00,79.200000,79.2000
877,19.00,7.8958,0,0,19.000000,19.00,7.895800,7.8958
847,35.00,7.8958,0,0,35.000000,35.00,7.895800,7.8958
848,28.00,33.0000,1,0,28.000000,28.00,33.000000,33.0000
475,NaN,52.0000,0,0,29.699118,28.00,52.000000,52.0000
373,22.00,NaN,0,0,22.000000,22.00,32.279338,14.4542
822,38.00,0.0000,0,0,38.000000,38.00,0.000000,0.0000
803,0.42,8.5167,1,1,0.420000,0.42,8.516700,8.5167

In [43]:
X_train.head()

      Age     Fare  Family
331  45.5  28.5000       0
733  23.0  13.0000       0
382  32.0   7.9250       0
704  26.0   7.8542       1
813   6.0  31.2750       6

In [44]:
y_test.head()

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64

In [47]:
imputer1=SimpleImputer(strategy='median')
imputer2=SimpleImputer(strategy='mean')

In [50]:
trf=ColumnTransformer([
    ('imputer1', imputer1,['Age']),
    ('imputer2', imputer2,['Fare'])
],remainder='passthrough')

In [54]:
trf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer1', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('imputer2', SimpleImputer(), ['Fare'])])

In [56]:
X_train_transformed=trf.transform(X_train)
X_test_transformed=trf.transform(X_test)

In [60]:
X_train_transformed

array([[ 45.5       ,  28.5       ,   0.        ],
       [ 23.        ,  13.        ,   0.        ],
       [ 32.        ,   7.925     ,   0.        ],
       ...,
       [ 41.        ,  32.51778772,   2.        ],
       [ 14.        , 120.        ,   3.        ],
       [ 21.        ,  77.2875    ,   1.        ]])