In [1]:
import numpy as np 
import pandas as pd

In [11]:
from sklearn.model_selection import train_test_split 
from sklearn.impute import MissingIndicator,SimpleImputer

In [3]:
df=pd.read_csv('titanic_toy.csv')

In [4]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [5]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [8]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(['Survived'],axis=1),
                                              df['Survived'],
                                              test_size=.3,
                                              random_state=42)
X_train.shape,y_train.shape

((623, 3), (623,))

In [9]:
# check the accuracy without missing indicator

In [33]:
si=SimpleImputer()
X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)
X_train_trf

array([[  4.        ,  81.8583    ,   2.        ],
       [ 29.25635271,   7.8958    ,   0.        ],
       [  1.        ,  11.1333    ,   2.        ],
       ...,
       [ 41.        ,  31.79834806,   2.        ],
       [ 14.        , 120.        ,   3.        ],
       [ 21.        ,  77.2875    ,   1.        ]])

In [25]:
from sklearn.linear_model import LogisticRegression 
clf=LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_pred)

0.6567164179104478

In [26]:
# check the accuracy score using the missing  indicator

In [43]:
mi=MissingIndicator()
X_train_missing=mi.fit_transform(X_train)
X_test_missing=mi.transform(X_test)

In [44]:
X_test_missing

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False],
       [False, False],
       [False, False]])

In [49]:
X_train[['Age_NA','Fare_NA']]=X_train_missing
X_train

      Age      Fare  Family  Age_NA  Fare_NA
445   4.0   81.8583       2   False    False
650   NaN    7.8958       0    True    False
172   1.0   11.1333       2   False    False
450  36.0   27.7500       3   False    False
314  43.0   26.2500       2   False    False
..    ...       ...     ...     ...      ...
106  21.0    7.6500       0   False    False
270   NaN   31.0000       0    True    False
860  41.0       NaN       2   False     True
435  14.0  120.0000       3   False    False
102  21.0   77.2875       1   False    False

[623 rows x 5 columns]

In [51]:
X_test[['Age_NA','Fare_NA']]=X_test_missing
X_test

      Age     Fare  Family  Age_NA  Fare_NA
709   NaN  15.2458       2    True    False
439  31.0  10.5000       0   False    False
840  20.0   7.9250       0   False    False
720   6.0  33.0000       1   False    False
39   14.0  11.2417       1   False    False
..    ...      ...     ...     ...      ...
821  27.0   8.6625       0   False    False
633   NaN      NaN       0    True     True
456  65.0  26.5500       0   False    False
500  17.0   8.6625       0   False    False
430  28.0  26.5500       0   False    False

[268 rows x 5 columns]

In [53]:
si=SimpleImputer()
X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)

In [54]:
clf=LogisticRegression()
clf.fit(X_train_trf2,y_train)
y_pred=clf.predict(X_test_trf2)
accuracy_score(y_test,y_pred)

0.6567164179104478