In [24]:
import numpy as np
import pandas as pd
df=pd.read_csv("Titanic.csv")

# How big is data

In [12]:
df.shape

(891, 16)

# How Does Data Looks Like ?

In [13]:
df.sample(5)

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
372,372,0,3,male,19.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
726,726,1,2,female,30.0,3,0,21.0000,S,Second,woman,False,NaN,Southampton,yes,False
858,858,1,3,female,24.0,0,3,19.2583,C,Third,woman,False,NaN,Cherbourg,yes,False
208,208,1,3,female,16.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True

# What is the Data Type of of COls

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    int64
 3   sex          891 non-null    str
 4   age          714 non-null    float64
 5   sibsp        891 non-null    int64
 6   parch        891 non-null    int64
 7   fare         891 non-null    float64
 8   embarked     889 non-null    str
 9   class        891 non-null    str
 10  who          891 non-null    str
 11  adult_male   891 non-null    bool
 12  deck         203 non-null    str
 13  embark_town  889 non-null    str
 14  alive        891 non-null    str
 15  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(5), str(7)
memory usage: 99.3 KB

# Are there any Missing Value ?

In [16]:
df.isnull().sum()

Unnamed: 0       0
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# How Does the Data Look Mathematically

In [17]:
df.describe()

,Unnamed: 0,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,445.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,445.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,667.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,890.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# Are There any Duplicate?

In [21]:
df.duplicated().sum()

np.int64(0)

# How is the corelation between columns?

In [30]:
df.corr(numeric_only=True)['survived']

Unnamed: 0   -0.005007
survived      1.000000
pclass       -0.338481
age          -0.077221
sibsp        -0.035322
parch         0.081629
fare          0.257307
adult_male   -0.557080
alone        -0.203367
Name: survived, dtype: float64

In [31]:
df.corr(numeric_only=True)

,Unnamed: 0,survived,pclass,age,sibsp,parch,fare,adult_male,alone
Unnamed: 0,1.000000,-0.005007,-0.035144,0.036847,-0.057527,-0.001652,0.012658,0.041010,0.057462
survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307,-0.557080,-0.203367
pclass,-0.035144,-0.338481,1.000000,-0.369226,0.083081,0.018443,-0.549500,0.094035,0.135207
age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067,0.280328,0.198270
sibsp,-0.057527,-0.035322,0.083081,-0.308247,1.000000,0.414838,0.159651,-0.253586,-0.584471
parch,-0.001652,0.081629,0.018443,-0.189119,0.414838,1.000000,0.216225,-0.349943,-0.583398
fare,0.012658,0.257307,-0.549500,0.096067,0.159651,0.216225,1.000000,-0.182024,-0.271832
adult_male,0.041010,-0.557080,0.094035,0.280328,-0.253586,-0.349943,-0.182024,1.000000,0.404744
alone,0.057462,-0.203367,0.135207,0.198270,-0.584471,-0.583398,-0.271832,0.404744,1.000000