In [3]:
import numpy as np 
import pandas as pd 
df=pd.read_csv("cars.csv")

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [5]:
df.sample(10)

         brand  km_driven    fuel         owner  selling_price
5864    Maruti       7400  Diesel   First Owner         925000
648     Jaguar      45000  Diesel   First Owner        3200000
7779    Maruti      15000  Petrol   First Owner         282000
6083     Honda      60000  Petrol   First Owner         265000
7388    Maruti      80000  Petrol   First Owner         110000
6773     Skoda      35000  Diesel  Second Owner         850000
4063   Hyundai      25000  Petrol   First Owner         425000
5845   Renault      21900  Petrol   First Owner         360000
299    Hyundai      50000  Petrol   First Owner         525000
1606  Mahindra      90000  Diesel   Third Owner         550000

In [6]:
df.shape

(8128, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [8]:
df.isnull()

      brand  km_driven   fuel  owner  selling_price
0     False      False  False  False          False
1     False      False  False  False          False
2     False      False  False  False          False
3     False      False  False  False          False
4     False      False  False  False          False
...     ...        ...    ...    ...            ...
8123  False      False  False  False          False
8124  False      False  False  False          False
8125  False      False  False  False          False
8126  False      False  False  False          False
8127  False      False  False  False          False

[8128 rows x 5 columns]

In [9]:
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [14]:
df.duplicated().sum()

1678

In [19]:
df.corr(numeric_only=True)["selling_price"]

km_driven       -0.225534
selling_price    1.000000
Name: selling_price, dtype: float64

In [21]:
df.corr()["fuel"]

ValueError: could not convert string to float: 'Maruti'