In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("cars.csv")

In [3]:
df.sample(5)

        brand  km_driven    fuel         owner  selling_price
1858    Lexus      20000  Petrol   First Owner        5150000
1126   Toyota      25538  Petrol   First Owner         625000
6374   Maruti      15000  Petrol   First Owner         400000
3895   Toyota     120000  Diesel  Second Owner         525000
3216  Hyundai      60000     LPG  Second Owner         175000

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_test, y_train=train_test_split(df.drop(["selling_price"],axis=1),
                                                  df["selling_price"],
                                                  test_size=.3,
                                                  random_state=42)
X_train.head()

       brand  km_driven    fuel         owner
6783  Maruti     120000  Petrol   Third Owner
1073  Toyota     100000  Diesel   First Owner
7756     BMW      39000  Diesel   First Owner
144   Toyota      39000  Petrol   First Owner
6424  Maruti      70000  Diesel  Second Owner

In [8]:
from sklearn.compose import ColumnTransformer

In [ ]:
ct=ColumnTransformer(transformer=[
                     ('tns1',OneHotEncoder(Sparse=Fa,)
                     ()
                     ()
                     ]reminder='passthrough')