In [2]:
import numpy as np 
import pandas as pd

In [3]:
df=pd.read_csv("Social_Network_Ads.csv")

In [4]:
df.sample(5)

      User ID  Gender  Age  EstimatedSalary  Purchased
318  15742204    Male   45            32000          1
122  15724423  Female   40            75000          0
160  15744279    Male   32           100000          1
75   15651983    Male   34           112000          1
32   15573452  Female   21            16000          0

In [6]:
new_df=df.drop(columns=['Gender','User ID'])

In [15]:
new_df.shape
new_df.sample(5)

     Age  EstimatedSalary  Purchased
129   26            84000          0
183   33            43000          0
85    31           118000          1
185   31            66000          0
388   47            34000          1

In [16]:
new_df.shape

(400, 3)

In [8]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(new_df.drop("Purchased",axis=1),
                                              new_df["Purchased"],
                                              test_size=0.3,
                                              random_state=42
                                             )
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((280, 2), (120, 2), (280,), (120,))

In [21]:
np.round(X_train.describe())

         Age  EstimatedSalary
count  280.0            280.0
mean    38.0          70589.0
std     10.0          33949.0
min     18.0          15000.0
25%     30.0          44000.0
50%     37.0          71000.0
75%     45.0          88000.0
max     60.0         150000.0

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler=MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()

In [19]:
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [22]:
X_train_scaled

array([[0.26190476, 0.44444444],
       [0.47619048, 0.48148148],
       [0.64285714, 0.08148148],
       [0.85714286, 0.68888889],
       [0.66666667, 0.05925926],
       [0.11904762, 0.0962963 ],
       [0.45238095, 0.44444444],
       [0.57142857, 0.37037037],
       [0.4047619 , 0.41481481],
       [0.78571429, 0.97037037],
       [0.5       , 0.6       ],
       [0.14285714, 0.54814815],
       [0.95238095, 0.59259259],
       [0.16666667, 0.05185185],
       [0.54761905, 0.32592593],
       [0.23809524, 0.54814815],
       [0.57142857, 0.48148148],
       [0.57142857, 0.68888889],
       [0.66666667, 0.6       ],
       [0.69047619, 0.72592593],
       [0.35714286, 0.0962963 ],
       [0.02380952, 0.07407407],
       [0.73809524, 0.54814815],
       [0.30952381, 0.        ],
       [0.28571429, 0.47407407],
       [0.71428571, 0.93333333],
       [0.33333333, 0.75555556],
       [0.45238095, 0.41481481],
       [0.        , 0.52592593],
       [0.57142857, 0.47407407],
       [0.21428571, 0.51111111],
       [0.52380952, 0.37037037],
       [0.92857143, 0.43703704],
       [0.19047619, 0.        ],
       [0.19047619, 0.48148148],
       [0.26190476, 0.20740741],
       [0.35714286, 0.99259259],
       [0.5       , 0.2       ],
       [0.85714286, 0.65925926],
       [0.42857143, 0.13333333],
       [0.66666667, 0.12592593],
       [0.52380952, 0.94074074],
       [0.45238095, 0.34814815],
       [0.26190476, 0.98518519],
       [0.45238095, 0.31111111],
       [0.4047619 , 0.25925926],
       [0.57142857, 0.28148148],
       [0.4047619 , 0.17037037],
       [0.54761905, 0.11111111],
       [0.52380952, 0.42222222],
       [0.19047619, 0.        ],
       [0.30952381, 0.39259259],
       [0.4047619 , 0.28148148],
       [0.4047619 , 0.07407407],
       [0.28571429, 0.54814815],
       [0.54761905, 0.42222222],
       [0.23809524, 0.8       ],
       [0.66666667, 0.4962963 ],
       [0.0952381 , 0.35555556],
       [0.64285714, 0.05185185],
       [0.28571429, 0.25185185],
       [0.38095238, 0.07407407],
       [0.52380952, 0.44444444],
       [0.33333333, 0.75555556],
       [0.11904762, 0.4962963 ],
       [0.19047619, 0.48148148],
       [0.71428571, 0.85925926],
       [0.97619048, 0.94814815],
       [0.4047619 , 0.2962963 ],
       [0.38095238, 0.20740741],
       [0.5       , 0.34074074],
       [0.21428571, 0.6       ],
       [1.        , 0.5037037 ],
       [0.14285714, 0.2962963 ],
       [0.95238095, 0.95555556],
       [0.83333333, 0.65925926],
       [0.4047619 , 0.47407407],
       [0.42857143, 0.62222222],
       [0.92857143, 0.33333333],
       [0.45238095, 0.9037037 ],
       [0.35714286, 0.20740741],
       [0.54761905, 0.41481481],
       [0.80952381, 0.04444444],
       [0.80952381, 1.        ],
       [0.45238095, 0.40740741],
       [0.19047619, 0.51111111],
       [0.19047619, 0.42222222],
       [0.19047619, 0.27407407],
       [0.54761905, 0.33333333],
       [0.30952381, 0.37777778],
       [0.45238095, 0.95555556],
       [0.47619048, 0.34074074],
       [0.30952381, 0.14074074],
       [0.57142857, 0.44444444],
       [0.66666667, 0.75555556],
       [0.42857143, 0.27407407],
       [0.47619048, 0.41481481],
       [0.73809524, 0.54074074],
       [0.92857143, 0.13333333],
       [0.71428571, 0.91111111],
       [0.69047619, 0.25925926],
       [0.35714286, 0.4       ],
       [0.45238095, 0.97037037],
       [0.04761905, 0.4962963 ],
       [0.52380952, 0.23703704],
       [0.4047619 , 0.05185185],
       [0.04761905, 0.15555556],
       [0.64285714, 0.22222222],
       [0.19047619, 0.20740741],
       [0.95238095, 0.63703704],
       [0.52380952, 0.31111111],
       [0.47619048, 0.71851852],
       [0.45238095, 0.48148148],
       [0.73809524, 0.0962963 ],
       [0.42857143, 0.44444444],
       [0.54761905, 0.42222222],
       [0.4047619 , 0.33333333],
       [0.5952381 , 0.84444444],
       [0.54761905, 0.53333333],
       [0.47619048, 0.72592593],
       [0.95238095, 0.05925926],
       [0.19047619, 0.12592593],
       [0.33333333, 0.02222222],
       [0.54761905, 0.27407407],
       [0.30952381, 0.02222222],
       [0.4047619 , 0.54074074],
       [0.71428571, 0.14814815],
       [0.21428571, 0.54814815],
       [0.4047619 , 0.60740741],
       [0.57142857, 0.42962963],
       [0.07142857, 0.39259259],
       [0.54761905, 0.42222222],
       [0.35714286, 0.33333333],
       [0.5       , 0.88148148],
       [0.23809524, 0.51111111],
       [0.66666667, 0.54074074],
       [0.14285714, 0.31851852],
       [0.30952381, 0.76296296],
       [0.76190476, 0.54074074],
       [0.04761905, 0.4962963 ],
       [0.33333333, 0.88888889],
       [0.04761905, 0.52592593],
       [0.4047619 , 0.08888889],
       [0.26190476, 0.20740741],
       [0.07142857, 0.54074074],
       [0.4047619 , 0.32592593],
       [0.64285714, 0.12592593],
       [1.        , 0.2       ],
       [0.4047619 , 0.56296296],
       [0.4047619 , 0.21481481],
       [0.        , 0.21481481],
       [0.57142857, 0.99259259],
       [0.64285714, 0.47407407],
       [0.52380952, 0.33333333],
       [0.14285714, 0.05925926],
       [0.35714286, 0.26666667],
       [0.57142857, 0.40740741],
       [0.88095238, 0.85185185],
       [0.76190476, 0.21481481],
       [0.71428571, 0.77037037],
       [0.02380952, 0.45185185],
       [0.54761905, 0.42222222],
       [0.52380952, 0.41481481],
       [0.21428571, 0.54074074],
       [0.42857143, 0.82222222],
       [0.4047619 , 0.44444444],
       [0.4047619 , 0.31851852],
       [0.38095238, 0.74074074],
       [0.4047619 , 0.42962963],
       [1.        , 0.68888889],
       [0.16666667, 0.53333333],
       [0.21428571, 0.28888889],
       [0.07142857, 0.00740741],
       [0.45238095, 0.43703704],
       [0.4047619 , 0.17777778],
       [0.85714286, 0.40740741],
       [0.69047619, 0.11111111],
       [0.47619048, 0.25925926],
       [0.4047619 , 0.97777778],
       [0.4047619 , 0.45925926],
       [0.54761905, 0.47407407],
       [0.45238095, 0.13333333],
       [1.        , 0.22962963],
       [0.23809524, 0.32592593],
       [0.11904762, 0.37777778],
       [0.11904762, 0.35555556],
       [0.28571429, 0.01481481],
       [0.16666667, 0.13333333],
       [0.97619048, 0.5037037 ],
       [0.95238095, 0.17037037],
       [0.        , 0.4962963 ],
       [0.66666667, 0.32592593],
       [0.21428571, 0.01481481],
       [0.95238095, 0.23703704],
       [0.71428571, 0.11111111],
       [0.73809524, 0.37037037],
       [0.76190476, 0.15555556],
       [0.83333333, 0.42222222],
       [0.52380952, 0.31111111],
       [0.80952381, 0.73333333],
       [0.97619048, 0.2       ],
       [0.42857143, 0.35555556],
       [0.57142857, 0.65925926],
       [0.45238095, 0.27407407],
       [0.71428571, 0.13333333],
       [0.97619048, 0.1037037 ],
       [0.45238095, 0.47407407],
       [0.52380952, 0.34074074],
       [0.73809524, 0.43703704],
       [0.16666667, 0.55555556],
       [0.28571429, 0.        ],
       [0.52380952, 0.46666667],
       [0.14285714, 0.51111111],
       [0.47619048, 0.25925926],
       [0.64285714, 0.85925926],
       [0.07142857, 0.42222222],
       [0.4047619 , 0.05925926],
       [0.4047619 , 0.03703704],
       [0.30952381, 0.54814815],
       [0.28571429, 0.48148148],
       [0.69047619, 0.23703704],
       [0.21428571, 0.55555556],
       [0.4047619 , 0.42222222],
       [0.28571429, 0.74814815],
       [0.5       , 0.79259259],
       [0.26190476, 0.5037037 ],
       [0.54761905, 0.35555556],
       [0.71428571, 0.55555556],
       [0.47619048, 0.32592593],
       [0.33333333, 0.02222222],
       [0.5       , 0.44444444],
       [0.19047619, 0.48888889],
       [0.5       , 0.67407407],
       [0.0952381 , 0.2962963 ],
       [0.42857143, 0.76296296],
       [1.        , 0.2       ],
       [0.23809524, 0.2962963 ],
       [0.78571429, 0.88148148],
       [0.73809524, 0.0962963 ],
       [0.42857143, 0.33333333],
       [0.9047619 , 0.65925926],
       [0.21428571, 0.31851852],
       [0.14285714, 0.12592593],
       [0.38095238, 0.42222222],
       [0.23809524, 0.12592593],
       [0.76190476, 0.03703704],
       [0.35714286, 0.19259259],
       [0.26190476, 0.23703704],
       [0.0952381 , 0.02222222],
       [0.28571429, 0.88888889],
       [0.69047619, 0.66666667],
       [0.66666667, 0.47407407],
       [0.71428571, 0.88148148],
       [0.69047619, 0.25185185],
       [0.73809524, 0.93333333],
       [0.33333333, 0.62962963],
       [0.47619048, 0.41481481],
       [0.02380952, 0.08148148],
       [0.45238095, 0.45925926],
       [0.69047619, 0.26666667],
       [0.52380952, 0.31111111],
       [0.42857143, 0.81481481],
       [0.04761905, 0.43703704],
       [0.30952381, 0.31851852],
       [0.54761905, 0.22222222],
       [0.57142857, 0.28888889],
       [0.23809524, 0.16296296],
       [0.5       , 0.42962963],
       [0.23809524, 0.51851852],
       [0.47619048, 0.26666667],
       [0.69047619, 0.20740741],
       [0.45238095, 0.42222222],
       [0.73809524, 0.15555556],
       [0.64285714, 0.05185185],
       [0.4047619 , 0.42222222],
       [0.14285714, 0.08888889],
       [0.19047619, 0.14814815],
       [0.5952381 , 0.87407407],
       [0.5       , 0.45925926],
       [0.33333333, 0.52592593]])

In [20]:
np.round(X_train.describe())

         Age  EstimatedSalary
count  280.0            280.0
mean    38.0          70589.0
std     10.0          33949.0
min     18.0          15000.0
25%     30.0          44000.0
50%     37.0          71000.0
75%     45.0          88000.0
max     60.0         150000.0

In [26]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)

In [28]:
X_train_scaled.sample(10)

          Age  EstimatedSalary
4    0.666667         0.059259
204  0.714286         0.133333
135  0.666667         0.540741
89   0.309524         0.377778
269  0.476190         0.266667
275  0.142857         0.088889
3    0.857143         0.688889
96   0.476190         0.414815
133  0.500000         0.881481
81   0.547619         0.414815