In [1]:
import numpy as np 
import pandas as pd

In [4]:
df=pd.read_csv("cars.csv")

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [8]:
df["brand"].nunique()

32

In [9]:
df["fuel"].nunique()

4

In [10]:
df["owner"].nunique()

5

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(["selling_price"],axis=1),
                                               df["selling_price"],
                                               test_size=.2,
                                               random_state=42)
X_train.shape,X_test.shape

((6502, 4), (1626, 4))

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
ohe=OneHotEncoder(drop='first',dtype=np.int32)

In [37]:
X_train_encoded=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_encoded=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [30]:
X_train_encoded

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [47]:
new_df=np.hstack((X_train[['brand','km_driven']].values,X_train_encoded))

In [48]:
new_df

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [54]:
# Convert encoded array to DataFrame
encoded_df = pd.DataFrame(X_train_encoded, columns=ohe.get_feature_names_out(), index=X_train.index)

# Concatenate along the columns (axis=1)
new_df = pd.concat([X_train[['brand', 'km_driven']], encoded_df], axis=1)

In [55]:
new_df

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6518,Tata,2560,0,0,1,0,0,0,0
6144,Honda,80000,0,0,1,0,1,0,0
6381,Hyundai,150000,1,0,0,1,0,0,0
438,Maruti,120000,1,0,0,0,1,0,0
5939,Maruti,25000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,1,0,0,0,0,0,0
5390,Maruti,80000,1,0,0,0,1,0,0
860,Hyundai,35000,0,0,1,0,0,0,0
7603,Maruti,27000,1,0,0,0,0,0,0
7270,Maruti,70000,0,0,1,0,1,0,0

# Top Category encoding

In [59]:
counts=df["brand"].value_counts()

In [61]:
df["brand"].nunique()
threshold = 100

In [62]:
reply=counts[counts<=threshold].index

In [65]:
pd.get_dummies(df["brand"].replace(reply,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False