In [1]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv("Social_Network_Ads.csv")
df.shape
new_df=df.drop(columns=['Gender','User ID'])

In [29]:
new_df.sample(10)

     Age  EstimatedSalary  Purchased
163   35            38000          0
268   47           144000          1
397   50            20000          1
46    25            79000          0
214   47            43000          0
68    22            63000          0
254   50            44000          0
376   46            74000          0
359   42            54000          0
357   41            72000          0

In [18]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test=train_test_split(new_df.drop("Purchased",axis=1),
                                               new_df["Purchased"],
                                               test_size=.2,
                                               random_state=42
                                              )
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((320, 2), (80, 2), (320,), (80,))

In [43]:
np.round(X_train.describe())

         Age  EstimatedSalary
count  320.0            320.0
mean    38.0          70281.0
std     10.0          34431.0
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          71000.0
75%     45.0          88000.0
max     60.0         150000.0

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [33]:
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [34]:
X_train_scaled

array([[-1.06675246, -0.38634438],
       [ 0.79753468, -1.22993871],
       [ 0.11069205,  1.853544  ],
       [ 0.60129393, -0.90995465],
       [ 1.87685881, -1.28811763],
       [-0.57615058,  1.44629156],
       [ 0.3069328 , -0.53179168],
       [ 0.99377543,  0.10817643],
       [-1.16487283,  0.45724994],
       [-1.55735433,  0.31180264],
       [ 1.0918958 ,  0.45724994],
       [-0.18366908, -0.47361276],
       [ 0.20881242, -0.32816546],
       [ 0.3069328 ,  0.28271318],
       [-1.16487283, -1.57901222],
       [ 0.11069205,  0.25362372],
       [ 2.07309956,  1.73718616],
       [ 0.40505317, -0.18271817],
       [ 1.4843773 ,  2.11534913],
       [-0.37990983,  1.21357589],
       [ 1.87685881,  1.50447048],
       [ 0.11069205,  0.02090805],
       [ 0.89565505, -1.31720709],
       [-1.36111358, -1.49174384],
       [-0.18366908, -0.5899706 ],
       [-0.57615058,  2.31897535],
       [ 0.99377543, -1.20084925],
       [-0.77239133,  1.06812859],
       [ 2.17121993, -1.05540195],
       [ 0.01257167, -0.26998655],
       [-0.4780302 , -1.14267033],
       [ 0.11069205,  0.02090805],
       [ 1.68061805, -0.90995465],
       [ 1.0918958 , -0.90995465],
       [ 0.50317355,  1.21357589],
       [-1.06675246, -1.46265438],
       [-1.16487283, -1.54992276],
       [-0.0855487 ,  0.66087616],
       [ 0.40505317, -0.47361276],
       [-0.28178945, -0.26998655],
       [-0.87051171,  0.13726589],
       [ 0.01257167,  0.28271318],
       [ 0.6994143 , -1.28811763],
       [ 1.58249768,  1.09721805],
       [ 0.79753468, -1.37538601],
       [-1.45923396, -1.22993871],
       [-0.0855487 ,  0.13726589],
       [ 0.40505317, -0.15362871],
       [-0.28178945,  0.02090805],
       [ 1.28813655,  2.20261751],
       [ 0.11069205,  0.74814454],
       [-1.36111358,  0.54451832],
       [ 1.97497918,  0.71905508],
       [-1.26299321, -1.40447546],
       [ 0.3069328 , -0.32816546],
       [-0.96863208,  0.54451832],
       [ 0.40505317,  0.28271318],
       [ 0.40505317,  1.09721805],
       [ 0.79753468,  0.74814454],
       [ 0.89565505,  1.24266535],
       [-0.4780302 , -1.22993871],
       [-1.85171546, -1.31720709],
       [ 1.0918958 ,  0.54451832],
       [-0.67427095, -1.60810168],
       [-0.77239133,  0.25362372],
       [ 0.99377543,  2.05717021],
       [-0.57615058,  1.35902318],
       [-0.0855487 ,  0.02090805],
       [-1.94983583,  0.45724994],
       [ 0.40505317,  0.25362372],
       [-1.06675246,  0.39907102],
       [ 0.20881242, -0.15362871],
       [ 1.87685881,  0.10817643],
       [-1.16487283, -1.60810168],
       [-1.16487283,  0.28271318],
       [-0.87051171, -0.79359682],
       [-0.4780302 ,  2.28988589],
       [ 0.11069205, -0.82268628],
       [ 1.58249768,  0.98086021],
       [-0.18366908, -1.08449141],
       [ 0.79753468, -1.11358087],
       [ 0.20881242,  2.08625967],
       [-0.0855487 , -0.24089709],
       [-0.87051171,  2.26079643],
       [-0.0855487 , -0.38634438],
       [-0.28178945, -0.5899706 ],
       [ 0.40505317, -0.50270222],
       [-0.28178945, -0.93904411],
       [ 0.3069328 , -1.17175979],
       [ 0.20881242,  0.04999751],
       [-1.16487283, -1.60810168],
       [-0.67427095, -0.06636033],
       [-0.28178945, -0.50270222],
       [-0.28178945, -1.31720709],
       [-0.77239133,  0.54451832],
       [ 0.3069328 ,  0.04999751],
       [-0.96863208,  1.53355994],
       [ 0.79753468,  0.3408921 ],
       [-1.55735433, -0.21180763],
       [ 0.6994143 , -1.40447546],
       [-0.77239133, -0.61906006],
       [-0.37990983, -1.31720709],
       [ 0.20881242,  0.13726589],
       [-0.57615058,  1.35902318],
       [-1.45923396,  0.3408921 ],
       [-1.16487283,  0.28271318],
       [ 0.99377543,  1.76627562],
       [ 2.07309956,  2.11534913],
       [-0.28178945, -0.4445233 ],
       [-0.37990983, -0.79359682],
       [ 0.11069205, -0.26998655],
       [-1.06675246,  0.74814454],
       [ 2.17121993,  0.36998156],
       [-1.36111358, -0.4445233 ],
       [ 1.97497918,  2.14443859],
       [ 1.4843773 ,  0.98086021],
       [-0.28178945,  0.25362372],
       [-0.18366908,  0.83541291],
       [ 1.87685881, -0.29907601],
       [-0.0855487 ,  1.94081237],
       [-0.4780302 , -0.79359682],
       [ 0.3069328 ,  0.02090805],
       [ 1.38625693, -1.43356492],
       [ 1.38625693,  2.31897535],
       [-0.0855487 , -0.00818141],
       [-1.16487283,  0.39907102],
       [-1.16487283,  0.04999751],
       [-1.16487283, -0.53179168],
       [ 0.3069328 , -0.29907601],
       [-0.67427095, -0.12453925],
       [-0.0855487 ,  2.14443859],
       [ 0.01257167, -0.26998655],
       [-0.67427095, -1.05540195],
       [ 0.40505317,  0.13726589],
       [ 0.79753468,  1.35902318],
       [-0.18366908, -0.53179168],
       [ 0.01257167,  0.02090805],
       [ 1.0918958 ,  0.51542886],
       [ 1.87685881, -1.08449141],
       [ 0.99377543,  1.96990183],
       [ 0.89565505, -0.5899706 ],
       [-0.4780302 , -0.03727087],
       [-0.0855487 ,  2.20261751],
       [-1.75359508,  0.3408921 ],
       [ 0.20881242, -0.67723898],
       [-0.28178945, -1.40447546],
       [-1.75359508, -0.99722303],
       [ 0.6994143 , -0.7354179 ],
       [-1.16487283, -0.79359682],
       [ 1.97497918,  0.89359183],
       [ 0.20881242, -0.38634438],
       [ 0.01257167,  1.21357589],
       [-0.0855487 ,  0.28271318],
       [ 1.0918958 , -1.22993871],
       [-0.18366908,  0.13726589],
       [ 0.3069328 ,  0.04999751],
       [-0.28178945, -0.29907601],
       [ 0.50317355,  1.7080967 ],
       [ 0.3069328 ,  0.4863394 ],
       [ 0.01257167,  1.24266535],
       [ 1.97497918, -1.37538601],
       [-1.16487283, -1.11358087],
       [-0.57615058, -1.5208333 ],
       [ 0.3069328 , -0.53179168],
       [-0.67427095, -1.5208333 ],
       [-0.28178945,  0.51542886],
       [ 0.99377543, -1.02631249],
       [-1.06675246,  0.54451832],
       [-0.28178945,  0.777234  ],
       [ 0.40505317,  0.07908697],
       [-1.65547471, -0.06636033],
       [ 0.3069328 ,  0.04999751],
       [-0.4780302 , -0.29907601],
       [ 0.11069205,  1.853544  ],
       [-0.96863208,  0.39907102],
       [ 0.79753468,  0.51542886],
       [-1.36111358, -0.35725492],
       [-0.67427095,  1.38811264],
       [ 1.19001618,  0.51542886],
       [-1.75359508,  0.3408921 ],
       [-0.57615058,  1.88263345],
       [-1.75359508,  0.45724994],
       [-0.28178945, -1.25902817],
       [-0.87051171, -0.79359682],
       [-1.65547471,  0.51542886],
       [-0.28178945, -0.32816546],
       [ 0.6994143 , -1.11358087],
       [ 2.17121993, -0.82268628],
       [-0.28178945,  0.60269724],
       [-0.28178945, -0.76450736],
       [-1.94983583, -0.76450736],
       [ 0.40505317,  2.28988589],
       [ 0.6994143 ,  0.25362372],
       [ 0.20881242, -0.29907601],
       [-1.36111358, -1.37538601],
       [-0.4780302 , -0.56088114],
       [ 0.40505317, -0.00818141],
       [ 1.68061805,  1.73718616],
       [ 1.19001618, -0.76450736],
       [ 0.99377543,  1.4172021 ],
       [-1.85171546,  0.16635535],
       [ 0.3069328 ,  0.04999751],
       [ 0.20881242,  0.02090805],
       [-1.06675246,  0.51542886],
       [-0.18366908,  1.62082832],
       [-0.28178945,  0.13726589],
       [-0.28178945, -0.35725492],
       [-0.37990983,  1.30084427],
       [-0.28178945,  0.07908697],
       [ 2.17121993,  1.09721805],
       [-1.26299321,  0.4863394 ],
       [-1.06675246, -0.47361276],
       [-1.65547471, -1.57901222],
       [-0.0855487 ,  0.10817643],
       [-0.28178945, -0.90995465],
       [ 1.58249768, -0.00818141],
       [ 0.89565505, -1.17175979],
       [ 0.01257167, -0.5899706 ],
       [-0.28178945,  2.23170697],
       [-0.28178945,  0.19544481],
       [ 0.3069328 ,  0.25362372],
       [-0.0855487 , -1.08449141],
       [ 2.17121993, -0.70632844],
       [-0.96863208, -0.32816546],
       [-1.45923396, -0.12453925],
       [-1.45923396, -0.21180763],
       [-0.77239133, -1.54992276],
       [-1.26299321, -1.08449141],
       [ 2.07309956,  0.36998156],
       [ 1.97497918, -0.93904411],
       [-1.94983583,  0.3408921 ],
       [ 0.79753468, -0.32816546],
       [-1.06675246, -1.54992276],
       [ 1.97497918, -0.67723898],
       [ 0.99377543, -1.17175979],
       [ 1.0918958 , -0.15362871],
       [ 1.19001618, -0.99722303],
       [ 1.4843773 ,  0.04999751],
       [ 0.20881242, -0.38634438],
       [ 1.38625693,  1.27175481],
       [ 2.07309956, -0.82268628],
       [-0.18366908, -0.21180763],
       [ 0.40505317,  0.98086021],
       [-0.0855487 , -0.53179168],
       [ 0.99377543, -1.08449141],
       [ 2.07309956, -1.20084925],
       [-0.0855487 ,  0.25362372],
       [ 0.20881242, -0.26998655],
       [ 1.0918958 ,  0.10817643],
       [-1.26299321,  0.57360778],
       [-0.77239133, -1.60810168],
       [ 0.20881242,  0.22453427],
       [-1.36111358,  0.39907102],
       [ 0.01257167, -0.5899706 ],
       [ 0.6994143 ,  1.76627562],
       [-1.65547471,  0.04999751],
       [-0.28178945, -1.37538601],
       [-0.28178945, -1.46265438],
       [-0.67427095,  0.54451832],
       [-0.77239133,  0.28271318],
       [ 0.89565505, -0.67723898],
       [-1.06675246,  0.57360778],
       [-0.28178945,  0.04999751],
       [-0.77239133,  1.32993372],
       [ 0.11069205,  1.50447048],
       [-0.87051171,  0.36998156],
       [ 0.3069328 , -0.21180763],
       [ 0.99377543,  0.57360778],
       [ 0.01257167, -0.32816546],
       [-0.57615058, -1.5208333 ],
       [ 0.11069205,  0.13726589],
       [-1.16487283,  0.31180264],
       [ 0.11069205,  1.03903913],
       [-1.55735433, -0.4445233 ],
       [-0.18366908,  1.38811264],
       [ 2.17121993, -0.82268628],
       [-0.96863208, -0.4445233 ],
       [ 1.28813655,  1.853544  ],
       [ 1.0918958 , -1.22993871],
       [-0.18366908, -0.29907601],
       [ 1.77873843,  0.98086021],
       [-1.06675246, -0.35725492],
       [-1.36111358, -1.11358087],
       [-0.37990983,  0.04999751],
       [-0.96863208, -1.11358087],
       [ 1.19001618, -1.46265438],
       [-0.4780302 , -0.85177573],
       [-0.87051171, -0.67723898],
       [-1.55735433, -1.5208333 ],
       [-0.77239133,  1.88263345],
       [ 0.89565505,  1.00994967],
       [ 0.79753468,  0.25362372],
       [ 0.99377543,  1.853544  ],
       [ 0.89565505, -0.61906006],
       [ 1.0918958 ,  2.05717021],
       [-0.57615058,  0.86450237],
       [ 0.01257167,  0.02090805],
       [-1.85171546, -1.28811763],
       [-0.0855487 ,  0.19544481],
       [ 0.89565505, -0.56088114],
       [ 0.20881242, -0.38634438],
       [-0.18366908,  1.59173886],
       [-1.75359508,  0.10817643],
       [-0.67427095, -0.35725492],
       [ 0.3069328 , -0.7354179 ],
       [ 0.40505317, -0.47361276],
       [-0.96863208, -0.96813357],
       [ 0.11069205,  0.07908697],
       [-0.96863208,  0.42816048],
       [ 0.01257167, -0.56088114],
       [ 0.89565505, -0.79359682],
       [-0.0855487 ,  0.04999751],
       [ 1.0918958 , -0.99722303],
       [ 0.6994143 , -1.40447546],
       [-0.28178945,  0.04999751],
       [-1.36111358, -1.25902817],
       [-1.16487283, -1.02631249],
       [ 0.50317355,  1.82445454],
       [ 0.11069205,  0.19544481],
       [-0.57615058,  0.45724994]])

In [44]:
np.round(X_train_scaled.describe())

         Age  EstimatedSalary
count  320.0            320.0
mean    -0.0              0.0
std      1.0              1.0
min     -2.0             -2.0
25%     -1.0             -1.0
50%     -0.0              0.0
75%      1.0              1.0
max      2.0              2.0

In [38]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)

In [39]:
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns)

In [40]:
X_test_scaled

         Age  EstimatedSalary
0   0.797535        -1.404475
1   2.073100         0.515429
2  -0.968632        -0.764507
3   0.993775         0.748145
4  -0.870512        -1.229939
..       ...              ...
75 -0.281789        -0.589971
76  1.778738         1.824455
77  1.582498        -1.288118
78 -0.281789        -0.677239
79 -0.085549         0.224534

[80 rows x 2 columns]

In [41]:
X_train_scaled

          Age  EstimatedSalary
0   -1.066752        -0.386344
1    0.797535        -1.229939
2    0.110692         1.853544
3    0.601294        -0.909955
4    1.876859        -1.288118
..        ...              ...
315 -1.361114        -1.259028
316 -1.164873        -1.026312
317  0.503174         1.824455
318  0.110692         0.195445
319 -0.576151         0.457250

[320 rows x 2 columns]